[project]
name = "ai-toolkit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.11"
dependencies = [
    "modal>=1.0.5",
    "oyaml>=1.0",
    "python-dotenv>=1.1.1",
]
